sudo: required
language: python
services:
- docker
env:
  matrix:
  - PY_VER=2.7.10
  - PY_VER=2.7.11
  - PY_VER=2.7.12
  - PY_VER=2.7.13
  - PY_VER=2.7.14
  - PY_VER=2.7.15
  - PY_VER=3.6.5
  - PY_VER=3.6.6
  - PY_VER=3.7.0
  global:
  - secure: viWPCQXn2OJU8PmvPtfqvlhnUpBsCVjv5vJCIoDcnC/JAxyCgk8ADuT8fx3FCTafcVCjHjpYCkxlpcGtxBSfQXBPjNOtIsrNGhso3ugK4pdsbM7W4HadwYEUZje5C/cNiu1qCD/zZqfSwJbAybGfLiimPMiRjaLAXGogKYJFWx3rvG/Qvd8zdRVhBEMS7ngUW3ZWQQohD+hVhstpPDQBkRKzwDpLmcNwBulQCCNMnIed8JtToGbqsY0bllbWW7gn/2Z8BaQU6jcixYuD+kwinQOxhwymRa8HeOac4Dll3j0vAbhoDA4Uspd3IPWqFJhmy2GsCDH/JuseOChTwTRExA4i4xDNBXOhLg8eYZ0NlZ5422JDhINxz5YScIpH65niD2aMvPTN/yswYOFcbQm2vJK6DEqEMoau8FdpVfnLYyVgkaTGxJqPzk9HF3Bv0dpUaDu5jCKKeoEOudV4C1jnFMmuU5pvzre2Im+CqTB0JoQMhlcQpHs4HLvp4WPyFma/0ru8R0vuC9+KFSXnWvXqLSj/TZ7cbsh0zWpVDgyGGXgd3PtkWAIku7uLxNUdmZPiAWzy8Ti4S5CdXZISyR4da28g9wXAgOoBBwYf+9Ch22xh31ieUozrYLyN+tss9Kqa9Cw6SMI4fAIw3jbadhuu1W0yXdHh/SAEWbF5IxIh/zc=
  - secure: 6r36UZhBgsBMKkE7RDTCWKpM1QLlSMzLmBmDH9PoHXxx4i3wsJcoGlGtxLLtbqxp8KHqO/1BjphdmwclWUjCU+FbifyRFLurN3+QJzU1lfyA+XD4FafUzhBVWY3c4g8sd6WVkLM2AfMcvKAhp/5uTMDJDefP3bFlYqDlKwQx8MRRa4cKEddvgf5g5lYljqAIkBqxmUMvUzYvPXS+tbRI+TaBORyCX+h/g0ns/7fVTu1uMQkzVZPmjUeOwhHOyVwK39B8y5I3pWp6RSh6q5RTvXWbDd6YuIM6QSSXYJyEM1TCUchkI5VrKCR5V17o5gPy2FMf9Tml1OOGWB4G+4HhlSMv0E+doWv7UNFfrvwlBayNyI0VJKnxJf/FAI9oHV5sQRwk9gGTYTb8anA4c6VPpy1K86+Vv/oMXF+Z/MbTtCJ2Z7BH46Kai+EeVLm3/DiUZyZKOws7a5GjmAvFT1NAoY3ZRhf8tlsAZKQC/+M3thdidGvANdhIKj2SjorNUo2skkJeU2/i4/lj4Vn9t4ilo14v9Ybm7CKwVjn7Unmo5WPeUDvAReVQ73So3RCly7rT7WcY5CRFTIdQVa1wos3g0gQDFeRoVr9lXk3BCN/wlYprTdh/dWUIxkE96xiTfYaHjzBVlDBkFCMKgMTUjB3Kuwhjgy1qvZIV4obQgTcsC58=
script:
- export IMAGE_NAME=docker.io/halotools/python_tester:${PY_VER}
- docker build -t ${IMAGE_NAME} --build-arg PY_VER=${PY_VER} .
- docker run -it --rm ${IMAGE_NAME} /opt/python/bin/python --version && docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD} && docker push ${IMAGE_NAME}
